<?php

/**
 * GoalPlanRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GoalPlanRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GoalPlanRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GoalPlanRelation');
    }
}