<?php

/**
 * LocalTaskRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LocalTaskRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LocalTaskRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LocalTaskRelation');
    }
}