<?php

/**
 * Local
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    SGArqBase
 * @subpackage model
 * @author     Donel Vazquez Zambrano
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Local extends BaseLocal {

    public function isUsed() {
        if ($this->getTasks()->count() > 0)
            return true;

        return false;
    }

    public function isReservedAtDate($start, $end, $totaskid = false) {
        $query = Doctrine_Query::create()
                ->select('t.*')
                ->from('Task t')
                ->leftJoin('t.Event e')
                ->leftJoin('t.Local l')
                ->where('l.id = ?', array($this->getId()))
                ->andWhere('(e.start >= ? AND e.start <= ?) OR (e.end >= ? AND e.end <= ?) OR (e.start <= ? AND e.end >= ?)', array($start, $end, $start, $end, $start, $end));

        if ($totaskid)
            $query = $query->addWhere('t.id != ?', $totaskid);

        $tasks = $query->execute();

        return count($tasks) > 0;
    }

    public function getAsArray() {
        $result = $this->toArray();
        if ($this->getLocal() && $this->getLocal()->getId() > 0)
            $result['Local'] = $this->getLocal()->getAsArray();
        return $result;
    }

}