<?php

/**
 * LocalTaskRelation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ZentroInstructorI
 * @subpackage model
 * @author     MSc. Donel Vazquez Zambrano
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class LocalTaskRelation extends BaseLocalTaskRelation
{

}