<?php

/**
 * PlanPersonRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlanPersonRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlanPersonRelationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlanPersonRelation');
    }
}