<?php

/**
 * Tasktype
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    SGArqBase
 * @subpackage model
 * @author     Donel Vazquez Zambrano
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tasktype extends BaseTasktype {

    public function isUsed() {
        if ($this->getTasks()->count() > 0)
            return true;

        return false;
    }

    public function getAsArray() {
        $result = $this->toArray();
        if ($this->getTasktype() && $this->getTasktype()->getId() > 0)
            $result['Tasktype'] = $this->getTasktype()->getAsArray();
        return $result;
    }

}