<?php

/**
 * Team
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    SGArqBase
 * @subpackage model
 * @author     Donel Vazquez Zambrano
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Team extends BaseTeam {

    public static function getMaxDeep() {
        $q = Doctrine_Query::create()
                ->select('MAX(t.path)')
                ->from('Team t');
        $array = $q->fetchOne()->toArray();

        return count(str_split('/', $array['MAX'])) - 1;
    }

    public function isUsed() {
//        if ($this->getTeams()->count() > 0)
//            return true;

        return false;
    }

    public function isChildOf($parent) {
        $team = $this;

        do {
            if ($team->getParentid() != NULL && ($team->getId() != $parent->getId()))
                $team = Doctrine::getTable('Team')->find($team->getParentid());
        }
        while ($team->getParentid() != NULL && ($team->getId() != $parent->getId()));

        if ($team->getId() == $parent->getId())
            return true;

        return false;
    }

}